name: Build alt kernel
on:
  workflow_run:
    workflows:
      - "Preparing for build"
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Maximizing build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Waiting for new commit to settle
        run: sleep 10

      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Building the alt kernel
        run: python3 kernel_build.py alt-chromeos-5.10

      - name: Uploading to ci-storage
        uses: actions/upload-artifact@v2
        with:
          name: alt-kernel
          retention-days: 1
          path: |
            bzImage-alt
            modules-alt.tar.xz
            kernel-alt.config