name: Build experiemental kernel
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  main:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - name: Maximizing build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Building the experiemental kernel
        run: bash build.sh chromeos-5.15
      
      - name: Deleting old exp release
        if: "contains(github.event.head_commit.message, 'dev')"
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: exp-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Creating new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: exp-build
          name: Experiemental build - ${{ github.event.head_commit.message }}
          prerelease: true
          body: |
            Experiemental 5.15 ChromeOS release
            
            Triggered by ${{ github.sha }} at ${{ github.event.repository.updated_at }}
          files: |
            bzImage*
            modules*
            System.map-eupnea*
            config-eupnea*
