name: Build kernel
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  main:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - name: Maximizing build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Generating release tag and setting prerelease
        id: tag
        run: |
          if echo ${{ github.event.head_commit.message }} | grep -c "dev"
          then
            echo "::set-output name=release_tag::dev-build"
            echo "::set-output name=release_type::true"
          else
            echo "::set-output name=release_tag::$(date +"%Y.%m.%d_%H-%M")"
            echo "::set-output name=release_type::false"
          fi
      
      - name: Preparing Changelog        
        run: |
          echo 'CHNGLG<<EOF' >> $GITHUB_ENV
          cat changelog.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      
      - name: Building the standard Kernel
        run: bash build.sh chromeos-5.10
      
      - name: Building the experiemental 5.15 Kernel
        run: bash build.sh chromeos-5.15
          
      - name: Building the legacy SKL/KBL Kernel
        # We're not building the below for now because of Google's kernel clusterfuck
        # Looks like the 5.10.70 commit was deleted and now 5.10.54 is used, which doesn't work.
        run: wget https://github.com/cb-linux/breath/releases/download/KernelDeliverySystem2022.06.24_14-10/{bzImage.alt,modules.alt.tar.xz}

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: assets-for-download
      #     path: |
      #       kernel/bzImage
      #       kernel/modules*
      
      - name: Deleting old dev release
        if: "contains(github.event.head_commit.message, 'dev')"
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: dev-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Creating new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: Kernel build - ${{ github.event.head_commit.message }}
          prerelease: ${{ steps.tag.outputs.release_type }}
          body: |
            ⚠ For SKL and KBL users - an old release of the 5.10.70 kernel is being distributed until I can find a backup of the source.
            
            Changelog:
            ```
            ${{ env.CHNGLG }}
            ```
            Kernel Delivery System - Triggered by ${{ github.sha }} at ${{ github.event.repository.updated_at }}
          files: |
            bzImage*
            modules*
            System.map-eupnea*
            config-eupnea*
