name: Build stable kernel
on:
  workflow_run:
    workflows:
      - prepare
    types:
      - completed
  workflow_dispatch:

jobs:
  stable:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - name: Maximizing build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Waiting for new commit
        run: sleep 10

      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Building the standard Kernel
        run: bash build.sh chromeos-5.10

      - name: Uploading to as artifact
        uses: actions/upload-artifact@v2
        with:
          name: stable-kernel
          retention-days: 1
          path: |
            bzImage
            modules.tar.xz
            System.map-eupnea
            config-eupnea