name: Publish
on:
  workflow_run:
    workflows: [ "Build stable kernel" ] # wait for stable, as it seems it takes the longest
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Generating release tag and setting prerelease
        id: tag
        run: |
          if echo ${{ github.event.head_commit.message }} | grep -c "dev"
          then
            echo "::set-output name=release_tag::dev-build"
            echo "::set-output name=release_type::true"
          else
            echo "::set-output name=release_tag::$(date +"%Y.%m.%d_%H-%M")"
            echo "::set-output name=release_type::false"
          fi

      - name: Preparing Changelog
        run: |
          echo 'CHNGLG<<EOF' >> $GITHUB_ENV
          cat changelog.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: creating tmp folder
        run: mkdir /tmp/artifacts

      - name: Download stable artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-stable.yml
          workflow_status: completed
          name: stable-kernel
          path: /tmp/artifacts/

      - name: Download alt artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-alt.yml
          workflow_status: completed
          name: alt-kernel
          path: /tmp/artifacts/

      - name: Download exp artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-exp.yml
          workflow_status: completed
          name: exp-kernel
          path: /tmp/artifacts/

      - name: Publishing new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: Kernel build - ${{ github.event.head_commit.message }}
          prerelease: ${{ steps.tag.outputs.release_type }}
          body: |
            Changelog:
            ```
            ${{ env.CHNGLG }}
            ```
            Triggered by ${{ github.sha }} at ${{ github.event.repository.updated_at }}
          files: |
            /tmp/artifacts/bzImage*
            /tmp/artifacts/modules*
            /tmp/artifacts/System.map-eupnea*
            /tmp/artifacts/config-eupnea*


